library(readxl)
Demand <- read_excel("C:/Users/Saurabh/Downloads/Demand.xlsx",skip=1)
View(Demand)
str(Demand)

summary(demand[,3:4])
dem_ItA <- ts(demand[,3], start=c(2002,1), end=c(2017,7), frequency=12) 
plot(dem_ItA)
dem_ItB <- ts(demand[,4], start=c(2002,1), end=c(2017,7), frequency=12) 
plot(dem_ItB)
ts.plot(dem_ItA, dem_ItB, gpars = list(col = c("black", "red")),xlab="year", ylab="demand") 
legend("topleft", colnames(demand[3:4]), col=1:ncol(demand), lty=1.9, cex=.45)
monthplot(dem_ItA)
boxplot (dem_ItA ~cycle(dem_ItA))
monthplot(dem_ItB)
boxplot (dem_ItA ~cycle(dem_ItB))
ItA_Sea <- stl(dem_ItA[,1], s.window="p") #constant seasonality 
plot(ItA_Sea)
ItB_Sea <- stl(dem_ItB[,1], s.window="p") #constant seasonality 
plot(ItB_Sea)
series_names <- c('Deseasoned', 'Actual') 
Deseason_ItA <- (ItA_Sea$time.series[,2]+ItA_Sea$time.series[,3]) 
ts.plot(dem_ItA, Deseason_ItA, col=c("red", "blue"), main="ItemA Demand vs Deseasoned Demand")
series_names <- c('Deseasoned', 'Actual') 
Deseason_ItB <- (ItB_Sea$time.series[,2]+ItB_Sea$time.series[,3]) 
ts.plot(dem_ItB, Deseason_ItB, col=c("red", "blue"), main="ItemB Demand vs Deseasoned Demand")
DataATrain <- window(dem_ItA, start=c(2002,1), end=c(2015,12), frequency=12) 
DataATest <- window(dem_ItA, start=c(2016,1), frequency=12) 

DataBTrain <- window(dem_ItB, start=c(2002,1), end=c(2015,12), frequency=12) 
DataBTest <- window(dem_ItB, start=c(2016,1), frequency=12)

install.packages("forecast")
library(forecast)
fcst.ItA.stl <- forecast(ItmATrn, method="rwdrift", h=19) 
fcst.ItB.stl <- forecast(ItmBTrn, method="rwdrift", h=19) 

VecA<- cbind(DataATest,fcst.ItA.stl$mean) 
VecB<- cbind(DataBTest,fcst.ItB.stl$mean)
MAPEA <- mean(abs(VecA[,1]-VecA[,2])/VecA[,1]) 
MAPEA  
Box.test(fcst.ItA.stl$residuals, lag=10, type="Ljung-Box")  
ts.plot(VecB, col=c("blue", "red"),xlab="year", ylab="demand", main="Quarterly Demand B: Actual vs Forecast")
MAPEB <- mean(abs(VecB[,1]-VecB[,2])/VecB[,1]) 
MAPEB 
Box.test(fcst.ItB.stl$residuals, lag=30, type="Ljung-Box")  
hwA <- HoltWinters(as.ts(DataATrain),seasonal="additive") 
hwA
plot(hwA)
hwAForecast <- forecast(hwA, h=19) 
VecA1 <- cbind(DataATest,hwAForecast) 

par(mfrow=c(1,1), mar=c(2, 2, 2, 2), mgp=c(3, 1, 0), las=0) 

ts.plot(VecA1[,1],VecA1[,2], col=c("blue","red"),xlab="year", ylab="demand", main="Demand A: Actual vs Forecast")
Box.test(hwAForecast$residuals, lag=20, type="Ljung-Box")
#install.packages("MLmetrics")
library(MLmetrics)
MAPE(VecA1[,1],VecA1[,2])hwB <- HoltWinters(as.ts(DataBTrain),seasonal="additive") 
hwB
plot(hwB)
hwBForecast <- forecast(hwB, h=19) 
VecB1 <- cbind(DataBTest,hwBForecast) 

par(mfrow=c(1,1), mar=c(2, 2, 2, 2), mgp=c(3, 1, 0), las=0) 

ts.plot(VecB1[,1],VecB1[,2], col=c("blue","red"),xlab="year", ylab="demand", main="Demand B: Actual vs Forecast")
Box.test(hwBForecast$residuals, lag=20, type="Ljung-Box")
MAPE(VecB1[,1],VecB1[,2])
library(tseries) 
adf.test(dem_ItA)
diff_dem_ItA <- diff(dem_ItA) 
plot(diff_dem_ItA)
adf.test(diff(dem_ItA))
library(tseries) 
adf.test(dem_ItB)
diff_dem_ItB <- diff(dem_ItB) 
plot(diff_dem_ItB)
adf.test(diff(dem_ItB))
acf(dem_ItA,lag=15)
acf(diff_dem_ItA, lag=15)
acf(dem_ItB,lag=15)
acf(diff_dem_ItB, lag=15)
acf(dem_ItA,lag=50)
acf(diff_dem_ItA, lag=50)
pacf(dem_ItA)
pacf(diff_dem_ItA)
acf(dem_ItB,lag=50)
acf(diff_dem_ItB, lag=50)
pacf(dem_ItB)
pacf(diff_dem_ItB)
ItA.arima.fit.train <- auto.arima(DataATrain, seasonal=TRUE) 
ItA.arima.fit.train
plot(ItA.arima.fit.train$residuals)
plot(ItA.arima.fit.train$x,col="blue")
lines(ItA.arima.fit.train$fitted,col="red",main="Demand A: Actual vs Forecast")
MAPE(ItA.arima.fit.train$fitted,ItA.arima.fit.train$x)
acf(ItA.arima.fit.train$residuals)
pacf(ItA.arima.fit.train$residuals)
Box.test(ItA.arima.fit.train$residuals, lag = 10, type = c("Ljung-Box"), fitdf = 0)
ArimafcastA <- forecast(ItA.arima.fit.train, h=19) 
VecA2 <- cbind(DataATest,ArimafcastA) 

par(mfrow=c(1,1), mar=c(2, 2, 2, 2), mgp=c(3, 1, 0), las=0) 

ts.plot(VecA2[,1],VecA2[,2], col=c("blue","red"),xlab="year", ylab="demand", main="Demand A: Actual vs Forecast")
ItB.arima.fit.train <- auto.arima(dem_ItB, seasonal=TRUE) 
ItB.arima.fit.train
plot(ItB.arima.fit.train$residuals)
plot(ItB.arima.fit.train$x,col="blue") 
lines(ItB.arima.fit.train$fitted,col="red", main="Demand B: Actual vs Forecast")
MAPE(ItB.arima.fit.train$fitted,ItB.arima.fit.train$x)
acf(ItB.arima.fit.train$residuals)
pacf(ItB.arima.fit.train$residuals)
Box.test(ItB.arima.fit.train$residuals, lag = 10, type = c("Ljung-Box"), fitdf = 0)
ArimafcastB <- forecast(ItB.arima.fit.train, h=19) 
VecB2 <- cbind(DataBTest,ArimafcastB) 

par(mfrow=c(1,1), mar=c(2, 2, 2, 2), mgp=c(3, 1, 0), las=0) 

ts.plot(VecB2[,1],VecB2[,2], col=c("blue","red"),xlab="year", ylab="demand", main="Demand B: Actual vs Forecast")
ItA.arima.fit <- auto.arima(dem_ItA, seasonal=TRUE) 
fcastA <- forecast(ItA.arima.fit, h=19) 

plot(fcastA)
fcastA
ItB.arima.fit <- auto.arima(dem_ItB, seasonal=TRUE) 
fcastB <- forecast(ItB.arima.fit, h=19) 

plot(fcastB)
fcastB
